### ISSUE TITLE
Changes to "Open Data"

### ISSUE THREAD

**Issue by tacurran** [jfcurran/20181120-digitalbusinessplatform#11]
@jfcurran add the following link under "Example"
https://github.com/Deutsche-Boerse/dbg-pds/blob/master/docs/data_dictionary.md

**Comment by tacurran** [comment]
@jfcurran in the graphic, "Collumns" should be spelled "Columns"
"Algorhythms" should be "Algorithms"
consider adding the word "Data" above the "Rows" and below the "Columns" icons

**Comment by tacurran** [comment]
@jfcurran deadline for the changes / close issues is 12:00 20.11

**Comment by jfcurran** [comment]
👍
