### ISSUE TITLE
Changes to "Application Programming Interface"

### ISSUE THREAD

**Issue by tacurran** [jfcurran/20181120-digitalbusinessplatform#12]
Easy to use/understand

func HandleLogin(w http.ResponseWriter, req *http.Request) {
  r.ParseForm()
  if r.Form["username"] == "test" && r.Form["password"] === "secret" {
    consent.Grant(w, r, ory.GrantConsentPayload{
    })
    return
  }
  w.Write([]byte("Invalid username or password.\n"))
}

**Comment by tacurran** [comment]
@jfcurran Add the following "Example" under "Essentials"

Deutsche Boerse Digital Business Platform
https://console.developer.deutsche-boerse.com/

Ory Hydra OAuth 2.0 OpenID Connect Server
https://github.com/ory/hydra

**Comment by tacurran** [comment]
@jfcurran due to space reason, I suggest to use the following example for 
column "Essential" add bullet under "Public":
Easy to use/understand
"API access rule"
{
  "matchesMethods": ["GET"],
  "matchesUrl": "http://mydomain.com/api/example",
  "mode": "authorized"
}

**Comment by jfcurran** [comment]
Please be advised, slide is becoming crowded - J

**Comment by tacurran** [comment]
@jfcurran good point.  I suggest 
in the first bullet add "Examples:" after ..."partners."
in column "Essentials" change " Deutsche Boerse Digital Business Platform" to just
"Digital Business Platform"
in column "Essentials" change "Ory Hydra Oauth 2.0 OpenID Connect Server" to just
"Ory Hydra Server"
In the graphic, delete the "API access rule" and just use
{
  "matchesMethods": ["GET"],
  "matchesUrl": "http://myapi.com/api/example",
  "mode": "authorized"
}

**Comment by jfcurran** [comment]
👍
